@startuml

/'SUBSYSTEMS'/

  component teleop {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/
    portin teleop.join_state_sub as "join_state_sub" #blue

/' PORTS FROM THE ORIGINAL NODE '/
  }

  ros1_cob.joint_state_pub --> teleop.join_state_sub

@enduml