@startuml

/'SUBSYSTEMS'/
component launch_visual {
  component robot_state_publisher {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/
    portin robot_state_publisher.joint_states as "joint_states" #blue
    portout robot_state_publisher.tf_pub_ros2 as "tf_pub_ros2" #blue
    portout robot_state_publisher.tf_static_pub_ros2 as "tf_static_pub_ros2" #blue
    portout robot_state_publisher.robot_description as "robot_description" #blue

/' PORTS FROM THE ORIGINAL NODE '/
  }

  component rviz2 {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/
    portin rviz2.cloud_in_sub_rviz as "cloud_in_sub_rviz" #blue
    portin rviz2.map_sub as "map_sub" #blue
    portin rviz2.robot_description_sub as "robot_description_sub" #blue

/' PORTS FROM THE ORIGINAL NODE '/
  }

 }
component cob_nav2 {
  component amcl {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/

/' PORTS FROM THE ORIGINAL NODE '/
  }

  component behavior_server {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/

/' PORTS FROM THE ORIGINAL NODE '/
  }

  component bt_navigator {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/
    portin bt_navigator.tf_sub as "tf_sub" #blue
    portin bt_navigator.tf_static_sub as "tf_static_sub" #blue

/' PORTS FROM THE ORIGINAL NODE '/
  }

  component controller_server {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/

/' PORTS FROM THE ORIGINAL NODE '/
  }

  component global_costmap {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/

/' PORTS FROM THE ORIGINAL NODE '/
  }

  component lifecycle_manager_localization {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/

/' PORTS FROM THE ORIGINAL NODE '/
  }

  component lifecycle_manager_navigation {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/

/' PORTS FROM THE ORIGINAL NODE '/
  }

  component local_costmap {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/

/' PORTS FROM THE ORIGINAL NODE '/
  }

  component map_server {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/

/' PORTS FROM THE ORIGINAL NODE '/
  }

  component planner_server {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/

/' PORTS FROM THE ORIGINAL NODE '/
  }

  component smoother_server {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/

/' PORTS FROM THE ORIGINAL NODE '/
  }

  component velocity_smoother {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/

/' PORTS FROM THE ORIGINAL NODE '/
  }

  component waypoint_follower {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/

/' PORTS FROM THE ORIGINAL NODE '/
  }

 }
component cob4_bringup {
 }

  component joy_node {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/
    portout joy_node.joy_pub as "joy_pub" #blue

/' PORTS FROM THE ORIGINAL NODE '/
  }

  component twist_mux {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/
    portout twist_mux._base_twist_controller_command as "/base/twist_controller/command" #blue
    portin twist_mux.cmd_vel_sub as "cmd_vel_sub" #blue

/' PORTS FROM THE ORIGINAL NODE '/
  }

  component teleop_twist_joy_node {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/
    portin teleop_twist_joy_node.joy as "joy" #blue
    portout teleop_twist_joy_node.cmd_vel as "cmd_vel" #blue

/' PORTS FROM THE ORIGINAL NODE '/
  }

  component slam_toolbox {

/' PORTS DEFINED AS AVAILABLE IN THE ROSSYSTEM FILE '/
    portin slam_toolbox.map_sub_slamtb as "map_sub_slamtb" #blue
    portin slam_toolbox.scan_sub as "scan_sub" #blue
    portout slam_toolbox.map as "map" #blue
    portout slam_toolbox.tf as "tf" #blue

/' PORTS FROM THE ORIGINAL NODE '/
  }

  joy_node.joy_pub --> teleop_twist_joy_node.joy
  teleop_twist_joy_node.cmd_vel --> twist_mux.cmd_vel_sub
  twist_mux._base_twist_controller_command --> base_driver_ros1._base_twist_controller_command_sub_ros1
  scan_unifier_ros1.scan_unified_ros1 --> slam_toolbox.scan_sub
  joint_state_publisher_ros1.joint_states_ros1 --> robot_state_publisher.joint_states
  robot_state_publisher_ros1._tf_ros1 --> bt_navigator.tf_sub
  robot_state_publisher_ros1._tf_static_ros1 --> bt_navigator.tf_static_sub
  slam_toolbox.map --> rviz2.map_sub

@enduml