teleop_twist_joy_node:
  ros__parameters:
    enable_button: 2
    enable_turbo_button: 5
    axis_angular_yaw: 0
    scale_angular_yaw: 0.4
    axis_linear_x: 1
    scale_linear_x: 0.7
    scale_linear_turbo_x: 1.5

