bridge_cob_navi_robot_topics/topics:
- topic: /base/twist_controller/command
  type: geometry_msgs/msg/Twist
- topic: /scan_unified
  type: sensor_msgs/msg/LaserScan
- topic: /joint_states
  type: sensor_msgs/msg/JointState
- topic: tf
  type: tf2_msgs/msg/TFMessage
- topic: tf_static
  type: tf2_msgs/msg/TFMessage
